title: Auli Viidalepp
description: academic website
website: https://auli.viidalepp.org
basewebsite: /
theme: jekyll-theme-minimal
show_downloads: false
nav: true
social: true
projects: true


defaults:
  -
    scope:
      path: ""
      type: "pages" # a collection in your site, in plural form
    values:
      layout: "default"